steps:
  # List GKE Clusters available on GCP Project & Connect to specific GKE cluster via gcloud
  # Get Acccess Token to be used by Helm 3 Registry to auth to GCP Artifact Registry
  - name: 'gcr.io/cloud-builders/gcloud'
    script: |
      #!/usr/bin/env bash
      gcloud container clusters list    
      gcloud container clusters get-credentials devops --region=us-central1
      gcloud auth application-default print-access-token > app-default-token.txt
  # Auth Helm 3 to GCP Artifact Registry & install chart on GCP GKE.
  - name: 'gcr.io/$PROJECT_ID/helm'
    script: |
      helm version
      cat app-default-token.txt | helm registry login -u oauth2accesstoken --password-stdin https://us-central1-docker.pkg.dev
      helm upgrade --force --install --namespace default my-rest-api . --values values.yaml
      helm list --namespace default
      helm status my-rest-api
