steps:
  # List GKE Clusters available on GCP Project
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['container', 'clusters', 'list']
  # Connect to GKE cluster via gcloud
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['container', 'clusters', 'get-credentials', 'devops', '--region=us-central1']
  # Get Acccess Token to be used by Helm 3 Registry to auth to Artifact Registry
  - name: 'gcr.io/cloud-builders/gcloud'
    script: |
      gcloud auth application-default print-access-token > app-default-token.txt
      cat app-default-token.txt
  - name: 'gcr.io/$PROJECT_ID/helm'
    script: |
      cat app-default-token.txt | helm registry login -u oauth2accesstoken --password-stdin https://us-central1-docker.pkg.dev
      helm upgrade --install --set image.tag=latest --namespace default my-rest-api . --values values.yaml
      helm list --namespace default
      helm status my-rest-api
